version = 0.1

[dev.deploy.parameters]
stack_name = "lambda-sam-app"
resolve_s3 = true
s3_prefix = "lambda-sam-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
